language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - stable
os:
  - linux
services:
  - mongodb
env:
  - NODE_ENV=development
install:
  - npm install -g coffee-script
  - npm install
script: make ci
